openapi: 3.0.3
info:
  title: users-service
  version: "1.0.0"
paths:
  /api/v1/users:
    post:
      summary: Crear usuario (registro)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: Usuario creado
          headers:
            Location:
              description: URI del recurso creado
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/v1/users/{userId}:
    get:
      summary: Obtener usuario por id
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: No encontrado
    put:
      summary: Reemplazar/actualizar perfil del usuario
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '200':
          description: Usuario actualizado
    patch:
      summary: Actualización parcial del usuario
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Usuario actualizado parcialmente
    delete:
      summary: Eliminar usuario (soft-delete)
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Usuario eliminado (soft)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Location:
      type: object
      properties:
        lat:
          type: number
        lon:
          type: number
        address:
          type: string
    UserCreate:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        password:
          type: string
    User:
      allOf:
        - $ref: '#/components/schemas/UserCreate'
        - type: object
          properties:
            userId:
              type: string
            createdAt:
              type: string
              format: date-time
  parameters:
    CorrelationId:
      name: X-Correlation-Id
      in: header
      schema:
        type: string
      required: false